### ISSUE TITLE
Update to salmon equivalence class format (gzipping) in new versions

### ISSUE THREAD

**Issue by rob-p** [SimoneTiberi/BANDITS#4]
Hi all,

  Hope you are well, and thanks for the interesting work! I’m just writing to let you know that, starting in salmon 1.2.0 (which was just released), the equivalence class output is gzipped by default.  This is something which should be easy to take clear of in your processing scripts (the format of the file remains identical to previous versions, its just that the text format file itself is now gzipped).  You should be able to simply check the file extension (or salmon version), and wrap the equivalence class reader in a gzip reader / stream.  This nicely compresses the size of the equivalence class files, which is particularly useful now that we also [have a downstream tool that relies on them in the output across multiple samples](https://github.com/COMBINE-lab/terminus).

—Rob

**Comment by SimoneTiberi** [comment]
Hi Rob,
Many thanks for letting me know!
I will edit BANDITS accordingly.

Have a good one,
Simone

**Comment by SimoneTiberi** [comment]
Issue fixed: added R.utils among Imports in DESCRIPTION file.
R.utils is needed by fread to read gzipped files; no edits to the code required.
