### ISSUE TITLE
Issues with large dataset

### ISSUE THREAD

**Issue by J-Lye** [SimoneTiberi/BANDITS#6]
I'm experiencing some issues with the BANDITS program when running a large dataset. It never seems to finish.

I'm a novice coder and so I've taken a few shortcuts a relocated all of the data files into the actual BANDITS software architecture to save me redirecting everything.  I'm running the program on about 160 samples, but am experiencing this error below. I did note that I only had 32 cores available when running, I'm not sure if that was the issue but have set to re-run with n_cores= 30. Expecting the same error though. Please advise anything you think might help?

```
input_data = create_data(salmon_or_kallisto = "salmon",
+                          gene_to_transcript = id_table,
+                          salmon_path_to_eq_classes = equiv_classes_files,
+                          eff_len = eff_len,
+                          n_cores =120,
+                          transcripts_to_keep = transcripts_to_keep)
Data has been loaded
One group of genes has 22138 genes
Splitting the group in 22138 groups of individual genes
Max  36  transcripts per group
Max  25  genes per group
> ##input filter
> input_data = filter_genes(input_data, min_counts_per_gene = 20)
Initial number of genes: 20358; number of selected genes: 20358
> 
> set.seed(61217)
> precision = prior_precision(gene_to_transcript = id_table,
+                             transcript_counts = counts,
+                             n_cores =120,
+                             transcripts_to_keep = transcripts_to_keep)
Estimating gene-wise precision parameters
Error in result[[njob]] <- value : 
attempt to select less than one element in OneIndex
Calls: prior_precision ... <Anonymous> -> <Anonymous> -> bploop -> bploop.lapply
In addition: Warning message:
In parallel::mccollect(wait = FALSE, timeout = 1) :
  1 parallel job did not deliver a result
Execution halted
Error while shutting down parallel: unable to terminate some child processes

```

**Comment by SimoneTiberi** [comment]
Hey @J-Lye,
I somehow missed your comment!
I never tried to use more cores than available, but I suspect `BiocParallel` should handle these cases or provide a clear error message...although the error seems connected to parallel computing.
Does the error persist when using 30 cores?

If so, happy to look at it if you can share the data (or part of it).

**Comment by J-Lye** [comment]
> Hey @J-Lye,
> I somehow missed your comment!
> I never tried to use more cores than available, but I suspect `BiocParallel` should handle these cases or provide a clear error message...although the error seems connected to parallel computing.
> Does the error persist when using 30 cores?
> 
> If so, happy to look at it if you can share the data (or part of it).

Running just 3x3, 6x6, and 9x9; I've seemingly fixed the issue of the job never finishing by reducing the max_genes_per_group to just 2.  My university is granting access to higher memory cores with extending running time so that I can run the job on all 160 samples.  I'm now only experiencing a minor technical difficulty which I hope you can help with. It pertains to the output format of results. 

I've tried saving this to a text file so that I might interrogate manually or using other programs, link to GO analysis etc. however below you can see the syntax, output and error ;

```
results

##write results to matrix, then dataframe, then text file
results_matrix<-as.matrix(results)
results_data_frame<-as.data.frame(results_matrix)
write.table(results_data_frame, file = "covid_vs_flu_DTU.txt", sep = "\t", row.names = TRUE, col.names = TRUE)
```

At the end of the script I get this error

Returning results

```
results

A 'BANDITS_test' object, with 15692 gene and 72882 transcript level results.

##write results to matrix, then dataframe, then text file
results_matrix<-as.matrix(results)

Error in as.vector(data) :
no method for coercing this S4 class to a vector
Calls: as.matrix -> as.vector
Execution halted
```

I've tried a few variations but not sure how to get my results out once they have successfully completed. I appreciate this is probably trivial compared with the processor question but still cant crack it after many attempts and variations. How can I print all of the result to a single text file?

**Comment by SimoneTiberi** [comment]
Hey @J-Lye,
glad it's working fine.

`max_genes_per_group` determined how to treat reads that map to multiple genes.
In such cases BANDITS creates groups of genes to be analyzed together.
By default `max_genes_per_group = 50`, which means BANDITS will create groups of max 50 genes.
If there are bigger groups than `max_genes_per_group`, reads mapping to multiple genes will be counted multiple times (once for every gene they are compatible with).
The extreme case is to use `max_genes_per_group  = 1`; just to put this in context: most methods double count multi-gene reads anyway, so it's not a big approximation anyway.

**In a nutshell**: using a bigger `max_genes_per_group` leads to marginal improvements in performance (particularly when lots of reads map to multiple genes), but it also increases (potentially a lot) the computational cost.

Regarding storing results: 
```
data("results", package = "BANDITS")
results
A 'BANDITS_test' object, with 37 gene and 116 transcript level results.
```

`results` are a `BANDITS_test` class object, not a data.frame or a matrix; in order to access reults you need to use accessor functions; see `help(BANDITS_test)`

To access gene- and transcript-level results into data.frames (which you can store via `write.table`):
```
results_genes = top_genes(results)
results_transcripts = top_transcripts(results)
```

**Comment by J-Lye** [comment]
Hi Simone, Thanks for this.

I'm sorry I still need a little further clarification on the printing of results. If I want to print ALL of the results to a text file. How can I do this without using the accessor functions. 
I tried this

`
Results_all <- write.table(results, file ="my_file_name.txt", sep ="\t", row.names=TRUE, col.names =TRUE)`

But got the same error

**Comment by SimoneTiberi** [comment]
Hi @J-Lye,
`results` are not a table or data.frame or matrix, so cannot be stored with write.table.
`results` contains a list of data.frames: 1 data.frame for gene-level results (`top_genes(results)`); 1 data.frame for transcript-level results (`top_transcripts(results)`); other secondary objects (as visible from `help(BANDITS_test)`).

If you want to store all results, you need to store them individually (e.g., gene-level and transcript-level in 2 different txt files).

I hope this helps.
Simone
