### ISSUE TITLE
Sample wise transcript abundance

### ISSUE THREAD

**Issue by J-Lye** [SimoneTiberi/BANDITS#8]
In order to further assess the impact of alternative splicing it would be particularly useful if I could print out a table of the relative transcript proportions per sample, rather than TPM counts. 

As this is key to the process, I imagine there is some way to do this before the group wise DTU is calculated? I'm intending to then perform multiple regression or lasso regression to identify the most important features on a transcript wise basis when compared with advancing age.

**Comment by SimoneTiberi** [comment]
Hi @J-Lye,
sample-specific transcript proportions are not stored (I think I avoided that for memory reasons; I might consider adding them in the future).
BANDITS only provides group-level estimates and posterior credible intervals.

If you are interested in sample-specific transcript-level relative abundance, you can easily obtain them by dividing transcript-level counts by the corresponding gene-level counts (or use TPMs if you want to accounts for different transcript lengths).

I hope this helps,
Simone
